filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
  # FIXME: Cannot reach the hosts of Logstash

# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]
#   username: "elastic"
#   password: "changeme"
setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme"